### Verbo GET – listar tudo
GET http://localhost:8000/produto/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET – listar
GET http://localhost:8000/produto/2 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
	"nome" : "Pastel de Frango da Camilly",
	"descricao" : "pastel de frango",
	"valor_unitario" : 10,
    "foto": "0010111"
     
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
	"nome" : "Pastel de Carne da Camilly editado",
	"descricao" : "pastel de carne",
	"valor_unitario" : 11,
    "foto": "1100101"
	
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/2 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

