### Verbo GET – listar
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar
GET http://localhost:8000/cliente/2 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
	"nome" : "Camilly Mescke Kahl ",
	"cpf" : "123456789193",
	"telefone": "23455543356",
	"compra_fiado" : 1,
	"dia_fiado" : 10,
	"senha" : "12345678"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
	"nome" : "Camilly Mescke Kahl editado",
	"cpf" : "123459115",
	"telefone": "23455542356",
	"compra_fiado" : 2,
	"dia_fiado" : 11,
	"senha" : "12343678"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/2 HTTP/1.1